### ISSUE TITLE
v5.1.0 included breaking change!

### ISSUE THREAD

**Issue by Arcanemagus** [evcohen/eslint-plugin-jsx-a11y#283]
It seems that [the commit](https://github.com/evcohen/eslint-plugin-jsx-a11y/commit/a14617528cda23c6c88902ace1d083e4e13ac271) removing `href-no-hash` was included in the v5.1.0 release.

_Note: Originally found by @Misiur in https://github.com/airbnb/javascript/issues/1474._

**Comment by ljharb** [comment]
Thanks for reporting - @evcohen, this will impact all users of the airbnb eslint config. I've created a new tag for `v5.1.1` that is [publishable](https://travis-ci.org/evcohen/eslint-plugin-jsx-a11y/builds/249749224), and reverts the breaking changes, and have pushed it up - if there's no objections, I'd like to publish this ASAP. (I've included `safe-publish-latest` which ensures that the backport won't accidentally publish as "latest", since v6 is latest).

@jessebeach, I'm still not sure if #236 was breaking or not; I'm proceeding under the assumption that it was not.

After v5.1.1 is published, I'll merge the tag back into master so as to incorporate the changelog changes (without leaving the tag orphaned).

**Comment by jessebeach** [comment]
> I'm still not sure if #236 was breaking or not; I'm proceeding under the assumption that it was not.

@ljharb It shouldn't be. It adds options, but the fallback is the old behavior.

**Comment by ljharb** [comment]
Thanks for confirming! That was my interpretation when reading the diff.

**Comment by ljharb** [comment]
Published v5.1.1.

**Comment by ljharb** [comment]
I put up #285 to get stamped so i can merge the tag in properly on the command line.

**Comment by evcohen** [comment]
ah thank you for taking care of this!!! my file system must have had the files removed when i checked out the 5.0.1 tag 😞

**Comment by ljharb** [comment]
The 5.0.1 tag sits on the 6.0.0 tag, so maybe the checkout just failed?

**Comment by inoas** [comment]
extends airbnb still shows this error but if you click the anchor you get to 404 page on github.

**Comment by ljharb** [comment]
@inoas it shouldn't if `npm ls` exits successfully.

**Comment by inoas** [comment]
well I include a11y independent of airbnb... this will soon be resolve I guess.
