### ISSUE TITLE
document about recommended way to manage generated ID

### ISSUE THREAD

**Issue by stevemao** [evcohen/eslint-plugin-jsx-a11y#528]
This issue has been brought up before in https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/51#issuecomment-240619945 and https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/51#issuecomment-283972947:

> Avoiding ids in a big app being worked on by a big team is ideal, and using a random hash function or uuid generator as a render-time id seems like a silly hack for associating a label with a form element, particularly when a valid solution for the majority (90+%) use case is as simple as <label><input /> Form label text</label>.

> Nested inputs take away a lot of overhead creating and managing system generated IDs in React.

I honest have run this issue many times. Since this project keeps both `htmlFor` and nesting as default, it might be good to add docs on how we should manage generated ID.

**Comment by ljharb** [comment]
IDs shouldn't be generated unless you're doing it on the server, so that server and client rendering are deterministic. Render-time uuids aren't just a hack, they're actually broken and should never be used.

To restate, every ID needs to be deterministic, on the server and the client, and guaranteed to be unique on the page. At Airbnb, for each input, we pass a required ID prop down from as far up the tree as possible to guarantee uniqueness.

Documenting these things better is a great idea.

**Comment by stevemao** [comment]
> every ID needs to be deterministic

Thanks! I did not think about that :)
