### ISSUE TITLE
`no-onchange` rule getting triggered on `<input />` and `<textarea />`

### ISSUE THREAD

**Issue by majapw** [evcohen/eslint-plugin-jsx-a11y#55]
The explanation for using `onBlur` instead of or in addition to `onChange` only makes references to `<select>` elements in its explanation, but gets blanket-applied to all inputs, including regular text input and text areas. Is this intentional? If so, can we talk a little bit about why `onChange` is problematic in this scenario?

**Comment by evcohen** [comment]
Yes this is intentional, but I'm not totally sure it's necessary. Definitely open for discussion about it. The main motivation behind it is that `onBlur` is an action that a keyboard only user deliberately makes when he/she intends to leave the input field. Avoiding `onChange` is intended to mean avoid doing things to the UI onChange because it can be confusing for a keyboard only user. However, of course you may need to do important things unrelated to UI on that event. That is why the rule passes when both are present. 

Like I said, I'm not 100% sure about this rule - it was taken from my former employer's a11y guide in an attempt to learn more about accessibility in general. Maybe we can have an option in the `.eslintrc` that allows the user to only apply this to `<select>` elements vs all inputs.

**Comment by octatone** [comment]
Hello, I was about to open a PR scoping the no-onchange rule to only apply to `select` and `option` as I am seeing this lint error on all my inputs where the rule's reference examples (navigating select menus) don't apply: https://github.com/octatone/eslint-plugin-jsx-a11y/commit/1dd7d9e2d6b3019318f3afbcf3b396f632db8f86

Should I scope this change to `.eslintrc` options?  I find the rule is overzealous given the reference material.

**Comment by evcohen** [comment]
@octatone thanks - LGTM 😄
