### ISSUE TITLE
div without interactive role passes jsx-a11y/no-noninteractive-element-interactions

### ISSUE THREAD

**Issue by sherzader** [evcohen/eslint-plugin-jsx-a11y#647]
`<li><div onClick={()={}}>{prop}</div></li>`
This passes the rule inspection, no errors. 
Doesn't it need an interactive role, like `role='button'`?

I don't see this case listed in the examples:
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-interactions.md#succeed

**Comment by jessebeach** [comment]
@sherzader this div is consider a "static" element because it has no inherent semantics. 

https://www.w3.org/TR/html-aria/#el-div

The example you provide fails `no-static-element-interactions`. If you add a non-interactive role to it, like `article`, then it would fail `no-noninteractive-element-interactions`. 

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/__tests__/src/rules/no-static-element-interactions-test.js#L264
